const state={screen:'recepcao',bootstrap:null,authorityCache:[],currentGuest:null,currentFamily:null,nomData:null,statsConfig:null};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const SGCM_READ_ACTIONS=new Set(['apiBootstrap','apiListarCerimonias','apiListarConvidados','apiObterConvidado','apiListarAutoridades','apiObterAutoridade','apiListarFamiliares','apiObterTribuna','apiListarNominata','apiListarMensagensNominata','apiEstatisticas','apiListarGruposEstatistica','apiOpcoesEstatistica','apiFotoBase64','apiResultadoComando']);
function apiUrl(){const u=String(window.SGCM_CONFIG?.API_URL||'').trim();if(!u||u.includes('COLE_AQUI'))throw new Error('Configure a URL do Apps Script em config.js.');return u;}
function jsonp(fn,args=[]){return new Promise((resolve,reject)=>{let done=false;const cb='__sgcm_cb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const cleanup=()=>{if(done)return;done=true;try{delete window[cb]}catch(e){window[cb]=undefined}if(s.parentNode)s.parentNode.removeChild(s);};const timer=setTimeout(()=>{cleanup();reject(new Error('Tempo excedido ao consultar o backend do SGCM.'));},30000);window[cb]=payload=>{clearTimeout(timer);cleanup();if(!payload||payload.ok===false)reject(new Error(payload?.error||'Erro no backend do SGCM.'));else resolve(payload.data);};const q=new URLSearchParams({action:fn,args:JSON.stringify(args),prefix:cb,_:String(Date.now())});s.src=apiUrl()+'?'+q.toString();s.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error('Não foi possível acessar o backend do SGCM.'));};document.head.appendChild(s);});}
async function writeCommand(fn,args=[]){const requestId='CMD_'+Date.now()+'_'+Math.random().toString(36).slice(2);const body=new URLSearchParams({requestId,action:fn,args:JSON.stringify(args)});try{await fetch(apiUrl(),{method:'POST',mode:'no-cors',body});}catch(e){throw new Error('Não foi possível enviar a alteração ao backend do SGCM.');}for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,i<6?350:600));const r=await jsonp('apiResultadoComando',[requestId]);if(!r?.pending){if(r.ok===false)throw new Error(r.error||'A operação não foi concluída.');return r.data;}}throw new Error('A operação foi enviada, mas o resultado não foi confirmado a tempo. Atualize a tela para conferir.');}
function server(fn,...args){return SGCM_READ_ACTIONS.has(fn)?jsonp(fn,args):writeCommand(fn,args);}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600);}
function openModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').classList.remove('hidden');}
function closeModal(e){if(e&&e.target!==$('#modalBackdrop'))return;$('#modalBackdrop').classList.add('hidden');$('#modal').innerHTML='';}
function modalCloseButton(){return '<button class="modal-close" onclick="closeModal()">FECHAR</button>';}
function toggleDrawer(on){$('#drawer').classList.toggle('open',on);$('#drawerBackdrop').classList.toggle('hidden',!on);}
function sideNavigate(s){toggleDrawer(false);navigate(s);}
function activeCeremony(){return state.bootstrap&&state.bootstrap.ativa;}
function contextCeremony(){return activeCeremony();}
function badgeStatus(s){const u=String(s||'').toUpperCase();if(u.includes('NÃO'))return '<span class="badge no">NÃO COMPARECERÁ</span>';if(u.includes('CONFIRM'))return '<span class="badge active">CONFIRMADO</span>';return '<span class="badge pending">PENDENTE</span>';}
function guestWarningsHtml(g){if(!g)return'';const out=[];if(g.CADASTRADO_BANCO===false)out.push('<span class="data-warning missing-bank">NÃO CADASTRADO NO BANCO</span>');else if(g.TEM_FOTO===false)out.push('<span class="data-warning no-photo">SEM FOTO</span>');const extras=(g.DADOS_FALTANTES||[]).filter(x=>x!=='FOTO'&&x!=='NÃO CADASTRADO EM AUTORIDADES');if(extras.length)out.push('<span class="data-warning">DADOS INCOMPLETOS</span>');return out.length?'<div class="data-warnings">'+out.join('')+'</div>':'';}
function photoHtml(p,cls='avatar'){if(!p||!p.FOTO_FILE_ID)return `<div class="${cls} placeholder">SEM FOTO</div>`;const url=p.FOTO_URL||'';return `<img class="${cls}" src="${esc(url)}" data-file-id="${esc(p.FOTO_FILE_ID)}" onerror="fallbackPhoto(this)" alt="Foto">`;}
async function fallbackPhoto(img){if(img.dataset.fallback==='1')return;img.dataset.fallback='1';try{const d=await server('apiFotoBase64',img.dataset.fileId);if(d)img.src=d;}catch(e){img.style.display='none';}}
async function reloadBootstrap(){state.bootstrap=await server('apiBootstrap');updateHeader();}
function updateHeader(){const a=activeCeremony(),h=$('#headerContext'),b=$('#contextBanner');h.textContent=a?`${a.NOME_EVENTO} | ${a.DATA?formatDate(a.DATA):''}`:'Nenhuma cerimônia ativa';if(!a){b.textContent='Nenhuma cerimônia está ATIVA. Ative uma cerimônia antes da operação.';b.classList.remove('hidden');}else b.classList.add('hidden');}
function formatDate(s){if(!s)return'';const p=String(s).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s;}
async function boot(){try{apiUrl();await reloadBootstrap();navigate(activeCeremony()?'recepcao':'cerimonias');}catch(e){$('#main').innerHTML=`<div class="notice danger-notice">${esc(e.message)}</div><div class="card"><p class="small">Se esta for a primeira publicação no GitHub, abra <b>config.js</b> e cole a URL /exec da implantação do Apps Script.</p></div>`;}}
function navigate(s){state.screen=s;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===s));const map={evento:renderEvento,recepcao:renderRecepcao,presentes:renderPresentes,familiares:renderFamiliares,cerimonias:renderCerimonias,autoridades:renderAutoridades,tribuna:renderTribuna,nominata:renderNominata,estatisticas:renderEstatisticas,documentos:renderDocumentos,guia:renderGuia};$('#main').innerHTML='<div class="loading">Carregando...</div>';Promise.resolve(map[s]?map[s]():renderRecepcao()).catch(e=>$('#main').innerHTML=`<div class="notice danger-notice">${esc(e.message)}</div>`);}
function refreshCurrent(){reloadBootstrap().then(()=>navigate(state.screen));}

async function renderCerimonias(){const list=await server('apiListarCerimonias');let html=`<div class="page-head"><div class="section-title">CERIMÔNIAS</div><button class="btn primary" onclick="openCeremonyForm()">NOVA CERIMÔNIA</button></div>`;if(!list.length)html+='<div class="empty">Nenhuma cerimônia cadastrada.</div>';else html+=list.map(c=>`<div class="card ${c.STATUS==='ATIVA'?'active-card':'standby-card'}"><div class="row between"><div class="grow"><div class="event-name">${esc(c.NOME_EVENTO)}</div><div class="small muted">${esc(formatDate(c.DATA))}${c.LOCAL?' | '+esc(c.LOCAL):''}</div><div class="small muted">Planilha: ${esc(c.ABA_CONVIDADOS)} / ${esc(c.ABA_FAMILIARES)}</div></div><span class="badge ${c.STATUS==='ATIVA'?'active':''}">${esc(c.STATUS)}</span></div><div class="actions">${c.STATUS==='ATIVA'?'<span class="small muted">Cerimônia operacional atual.</span>':`<button class="btn primary" onclick="activateCeremony('${c.ID_CERIMONIA}')">ATIVAR</button><button class="btn danger" onclick="deleteCeremony('${c.ID_CERIMONIA}')">EXCLUIR</button>`}<button class="btn outline" onclick="openCeremonyForm('${c.ID_CERIMONIA}')">EDITAR</button></div></div>`).join('');$('#main').innerHTML=html;}
function openCeremonyForm(id=''){const c=(state.bootstrap?.cerimonias||[]).find(x=>x.ID_CERIMONIA===id)||{};openModal(`${modalCloseButton()}<h2>${id?'Editar':'Nova'} cerimônia</h2><div class="field"><label>Nome</label><input id="ceName" value="${esc(c.NOME_EVENTO||'')}"></div><div class="grid2"><div class="field"><label>Data</label><input id="ceDate" type="date" value="${esc(c.DATA||'')}"></div><div class="field"><label>Local</label><input id="ceLocal" value="${esc(c.LOCAL||'')}"></div></div><button class="btn primary block" onclick="saveCeremony('${esc(id)}')">SALVAR</button>`);}
async function saveCeremony(id){await server('apiSalvarCerimonia',{ID_CERIMONIA:id,NOME_EVENTO:$('#ceName').value,DATA:$('#ceDate').value,LOCAL:$('#ceLocal').value});closeModal();await reloadBootstrap();renderCerimonias();}
async function activateCeremony(id){const atual=activeCeremony();if(atual&&!confirm(`A cerimônia atualmente ativa é "${atual.NOME_EVENTO}". Colocá-la em STANDBY e ativar a selecionada?`))return;await server('apiAtivarCerimonia',id);await reloadBootstrap();showToast('Cerimônia ativada.');renderCerimonias();}
async function deleteCeremony(id){if(!confirm('Excluir a cerimônia e suas duas abas de planejamento? Esta operação não pode ser desfeita.'))return;await server('apiExcluirCerimonia',id);await reloadBootstrap();renderCerimonias();}

async function renderEvento(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const guests=await server('apiListarConvidados',c.ID_CERIMONIA,'TODOS');$('#main').innerHTML=`<div class="section-title">EVENTO</div><div class="card active-card"><div class="event-name">${esc(c.NOME_EVENTO)}</div><div class="small muted">${esc(formatDate(c.DATA))}${c.LOCAL?' | '+esc(c.LOCAL):''}</div><div class="actions"><button class="btn primary" onclick="openAddGuest()">ADICIONAR CONVIDADO</button><button class="btn outline" onclick="navigate('tribuna')">TRIBUNA</button><button class="btn outline" onclick="navigate('nominata')">NOMINATA</button></div></div><div class="section-title">TODOS OS CONVIDADOS (${guests.length})</div>${personList(guests,true)}`;}
function personList(list,showStatus){if(!list.length)return'<div class="empty">Nenhum registro.</div>';return `<div class="person-list">${list.map(g=>`<div class="person-card clickable" onclick="openGuestDetail('${g.ID_CONVIDADO}')">${photoHtml(g)}<div class="grow"><div class="person-name">${esc((g.POSTO?g.POSTO+' ':'')+(g.NOME_GUERRA||g.NOME_COMPLETO))}</div><div class="person-sub">${esc(g.CARGO_ATUAL||g.NOME_COMPLETO)}</div>${guestWarningsHtml(g)}</div><div class="person-right">${g.PRESENCA?'<span class="badge present">PRESENTE</span>':(showStatus?badgeStatus(g.STATUS_CONFIRMACAO):'')}<div>${g.PRECEDENCIA<9999?'Preced. '+g.PRECEDENCIA:''}</div></div></div>`).join('')}</div>`;}
async function renderRecepcao(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const list=await server('apiListarConvidados',c.ID_CERIMONIA,'RECEPCAO');$('#main').innerHTML=`<div class="section-title">RECEPÇÃO — ${esc(c.NOME_EVENTO)}</div><div class="searchbar"><input id="recSearch" placeholder="Pesquisar por nome, posto ou cargo" oninput="filterVisiblePeople(this.value)"></div><div id="peopleArea">${personList(list,true)}</div>`;state.visiblePeople=list;}
async function renderPresentes(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const list=await server('apiListarConvidados',c.ID_CERIMONIA,'PRESENTES');$('#main').innerHTML=`<div class="section-title">PRESENTES — ${esc(c.NOME_EVENTO)} (${list.length})</div><div class="searchbar"><input placeholder="Pesquisar" oninput="filterVisiblePeople(this.value)"></div><div id="peopleArea">${personList(list,false)}</div>`;state.visiblePeople=list;}
function filterVisiblePeople(q){const x=String(q||'').toUpperCase(),list=(state.visiblePeople||[]).filter(g=>[g.NOME_COMPLETO,g.NOME_GUERRA,g.POSTO,g.CARGO_ATUAL].join(' ').toUpperCase().includes(x));$('#peopleArea').innerHTML=personList(list,true);}
async function openGuestDetail(id){const c=contextCeremony(),g=await server('apiObterConvidado',c.ID_CERIMONIA,id);if(!g)return;state.currentGuest=g;const missing=(g.DADOS_FALTANTES||[]);const warning=missing.length?`<div class="notice ${g.CADASTRADO_BANCO?'':'danger-notice'}"><b>Cadastro:</b> ${esc(missing.join(', '))}. O convidado continua normalmente na cerimônia; este aviso não bloqueia presença, tribuna ou nominata.</div>`:'';const bankAction=!g.CADASTRADO_BANCO?`<button class="btn primary" onclick="openRegisterGuestAuthority('${id}')">CADASTRAR NO BANCO</button>`:(missing.length&&g.ID_AUTORIDADE?`<button class="btn outline" onclick="openAuthorityForm('${g.ID_AUTORIDADE}')">COMPLETAR CADASTRO</button>`:'');openModal(`${modalCloseButton()}${photoHtml(g,'modal-photo')}<h2>${esc((g.POSTO?g.POSTO+' ':'')+(g.NOME_GUERRA||g.NOME_COMPLETO))}</h2>${warning}<dl class="detail-grid"><dt>Nome completo</dt><dd>${esc(g.NOME_COMPLETO)}</dd><dt>Cargo</dt><dd>${esc(g.CARGO_ATUAL)}</dd><dt>Status</dt><dd>${badgeStatus(g.STATUS_CONFIRMACAO)}</dd><dt>Precedência</dt><dd>${g.PRECEDENCIA}</dd><dt>Honras</dt><dd>${g.FAZ_JUS_HONRAS?'SIM':'NÃO'}</dd><dt>Pode presidir</dt><dd>${g.PODE_PRESIDIR?'SIM':'NÃO'}</dd></dl><div class="actions">${bankAction}${g.PRESENCA?`<button class="btn danger" onclick="guestPresence('${id}',false)">CANCELAR PRESENÇA</button>`:`<button class="btn ok" onclick="guestPresence('${id}',true)">CONFIRMAR PRESENÇA</button>`}<button class="btn secondary" onclick="changeGuestStatus('${id}')">ALTERAR STATUS</button><button class="btn outline" onclick="setRole('${id}','ANFITRIAO')">ANFITRIÃO</button><button class="btn outline" onclick="setRole('${id}','COANFITRIAO')">COANFITRIÃO</button><button class="btn outline" onclick="setRole('${id}','CORTE')">CORTE TRIBUNA</button><button class="btn outline" onclick="toggleExclude('${id}')">${g.EXCLUIR_TRIBUNA?'REINCLUIR NA TRIBUNA':'EXCLUIR DA TRIBUNA'}</button><button class="btn outline" onclick="addGuestToNominata('${id}')">ADICIONAR À NOMINATA</button><button class="btn secondary" onclick="moveGuest('${id}',-1)">SUBIR NA PRECEDÊNCIA</button><button class="btn secondary" onclick="moveGuest('${id}',1)">DESCER NA PRECEDÊNCIA</button></div>`);}
async function guestPresence(id,on){const c=contextCeremony();await server(on?'apiMarcarPresenca':'apiCancelarPresenca',c.ID_CERIMONIA,id);closeModal();navigate(state.screen);}
function changeGuestStatus(id){openModal(`${modalCloseButton()}<h2>Alterar status</h2><div class="field"><label>Status</label><select id="newStatus"><option>CONFIRMADO</option><option>PENDENTE</option><option>NÃO COMPARECERÁ</option></select></div><button class="btn primary block" onclick="saveGuestStatus('${id}')">SALVAR</button>`);}
async function saveGuestStatus(id){const c=contextCeremony();await server('apiAtualizarStatusConvidado',c.ID_CERIMONIA,id,$('#newStatus').value);closeModal();navigate(state.screen);}
async function setRole(id,role){const c=contextCeremony();await server('apiDefinirPapelConvidado',c.ID_CERIMONIA,id,role);closeModal();showToast('Definição atualizada.');}
async function toggleExclude(id){const c=contextCeremony();await server('apiToggleExcluirTribuna',c.ID_CERIMONIA,id);closeModal();showToast('Tribuna atualizada.');}
async function moveGuest(id,d){const c=contextCeremony();await server('apiMoverConvidado',c.ID_CERIMONIA,id,d);closeModal();navigate(state.screen);}
async function addGuestToNominata(id){const c=contextCeremony();await server('apiAdicionarItemNominata',{ID_CERIMONIA:c.ID_CERIMONIA,TIPO_ITEM:'AUTORIDADE',REFERENCIA_ID:id});closeModal();showToast('Autoridade adicionada à nominata.');}

async function openAddGuest(){const c=contextCeremony(),guests=await server('apiListarConvidados',c.ID_CERIMONIA,'TODOS');openModal(`${modalCloseButton()}<h2>Adicionar convidado</h2><div class="field"><label>Pesquisar no banco de autoridades</label><input id="agSearch" oninput="searchAuthorityForGuest()" placeholder="Nome, posto ou cargo"></div><div id="agResults" class="person-list"></div><div class="field"><label>Inserir em relação a</label><select id="agRef"><option value="">Final da lista</option>${guests.map(g=>`<option value="${g.ID_CONVIDADO}">${esc(g.PRECEDENCIA+' - '+g.POSTO+' '+g.NOME_GUERRA)}</option>`).join('')}</select></div><div class="field"><label>Posição</label><select id="agPos"><option value="DEPOIS">Depois</option><option value="ANTES">Antes</option></select></div><div class="actions"><button class="btn outline" onclick="openAuthorityForm('',true)">NOVA AUTORIDADE</button></div>`);}
async function searchAuthorityForGuest(){const q=$('#agSearch').value;if(q.length<2){$('#agResults').innerHTML='';return;}const rows=await server('apiListarAutoridades',q,30);$('#agResults').innerHTML=rows.map(a=>`<div class="person-card clickable" onclick="addSelectedAuthority('${a.ID_AUTORIDADE}')">${photoHtml(a)}<div class="grow"><div class="person-name">${esc(a.POSTO+' '+a.NOME_GUERRA)}</div><div class="person-sub">${esc(a.CARGO_ATUAL)}</div></div><div class="person-right">ADICIONAR</div></div>`).join('');}
async function addSelectedAuthority(id){const c=contextCeremony();await server('apiAdicionarConvidado',c.ID_CERIMONIA,{ID_AUTORIDADE:id,REFERENCIA_ID:$('#agRef').value,POSICAO:$('#agPos').value,STATUS_CONFIRMACAO:'PENDENTE'});closeModal();showToast('Convidado adicionado.');navigate('evento');}

async function openRegisterGuestAuthority(id){const c=contextCeremony(),g=await server('apiObterConvidado',c.ID_CERIMONIA,id);if(!g)return;openModal(`${modalCloseButton()}<h2>Cadastrar convidado no banco</h2><p class="small muted">A autoridade será inserida na aba AUTORIDADES na mesma posição relativa da precedência desta cerimônia. Foto e demais dados podem ser completados agora ou depois.</p><div class="grid2"><div class="field"><label>Posto / tratamento</label><input id="rgPosto" value="${esc(g.POSTO||'')}"></div><div class="field"><label>Nome de guerra</label><input id="rgGuerra" value="${esc(g.NOME_GUERRA||'')}"></div></div><div class="field"><label>Nome completo</label><input id="rgNome" value="${esc(g.NOME_COMPLETO||'')}"></div><div class="field"><label>Cargo atual</label><input id="rgCargo" value="${esc(g.CARGO_ATUAL||'')}"></div><div class="grid2"><div class="field"><label>Força / tipo</label><select id="rgForca"><option value="">Selecione</option>${['Aeronáutica','Marinha','Exército','Ministro da Defesa','Autoridade Civil','Militar Estrangeiro'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Situação</label><select id="rgSit"><option value="">Selecione</option><option>ATIVA</option><option>RESERVA</option></select></div></div><div class="grid2"><div class="field"><label>Sexo</label><select id="rgSexo"><option value=""></option><option>MASCULINO</option><option>FEMININO</option></select></div><div class="field"><label>Foto</label><input id="rgFoto" type="file" accept="image/*" capture="environment"></div></div><button class="btn primary block" onclick="saveGuestToBank('${id}')">SALVAR EM AUTORIDADES</button>`);}
async function saveGuestToBank(id){const c=contextCeremony(),f=$('#rgFoto').files[0],payload={POSTO:$('#rgPosto').value,NOME_COMPLETO:$('#rgNome').value,NOME_GUERRA:$('#rgGuerra').value,CARGO_ATUAL:$('#rgCargo').value,FORCA:$('#rgForca').value,SITUACAO:$('#rgSit').value,SEXO:$('#rgSexo').value};if(f){payload.FOTO_NOME=f.name;payload.FOTO_MIME=f.type;payload.FOTO_BASE64=await readFile(f);}await server('apiCadastrarConvidadoNoBanco',c.ID_CERIMONIA,id,payload);closeModal();showToast('Autoridade cadastrada no banco.');navigate(state.screen);}

async function renderAutoridades(){const list=await server('apiListarAutoridades','',500);state.authorityCache=list;$('#main').innerHTML=`<div class="page-head"><div class="section-title">AUTORIDADES</div><button class="btn primary" onclick="openAuthorityForm()">NOVA AUTORIDADE</button></div><div class="searchbar"><input id="autSearch" placeholder="Pesquisar banco" oninput="filterAuthorities(this.value)"></div><div id="autArea">${authorityList(list)}</div>`;}
function authorityList(list){return `<div class="person-list">${list.map(a=>`<div class="person-card clickable" onclick="openAuthorityForm('${a.ID_AUTORIDADE}')">${photoHtml(a)}<div class="grow"><div class="person-name">${esc((a.POSTO?a.POSTO+' ':'')+(a.NOME_GUERRA||a.NOME_COMPLETO))}</div><div class="person-sub">${esc(a.CARGO_ATUAL)}</div></div><div class="person-right">${esc(a.FORCA)}</div></div>`).join('')}</div>`;}
async function filterAuthorities(q){if(q.length<2){$('#autArea').innerHTML=authorityList(state.authorityCache||[]);return;}const list=await server('apiListarAutoridades',q,200);$('#autArea').innerHTML=authorityList(list);}
async function openAuthorityForm(id='',addAfter=false){const a=id?await server('apiObterAutoridade',id):{};openModal(`${modalCloseButton()}<h2>${id?'Editar':'Nova'} autoridade</h2>${a&&a.FOTO_FILE_ID?photoHtml(a,'modal-photo'):''}<div class="grid2"><div class="field"><label>Posto / tratamento</label><input id="aPosto" value="${esc(a?.POSTO||'')}"></div><div class="field"><label>Nome de guerra</label><input id="aGuerra" value="${esc(a?.NOME_GUERRA||'')}"></div></div><div class="field"><label>Nome completo</label><input id="aNome" value="${esc(a?.NOME_COMPLETO||'')}"></div><div class="field"><label>Cargo atual</label><input id="aCargo" value="${esc(a?.CARGO_ATUAL||'')}"></div><div class="grid2"><div class="field"><label>Força / tipo</label><select id="aForca"><option value="">Selecione</option>${['Aeronáutica','Marinha','Exército','Ministro da Defesa','Autoridade Civil','Militar Estrangeiro'].map(x=>`<option ${a?.FORCA===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Situação</label><select id="aSit"><option value="">Selecione</option><option ${a?.SITUACAO==='ATIVA'?'selected':''}>ATIVA</option><option ${a?.SITUACAO==='RESERVA'?'selected':''}>RESERVA</option></select></div></div><div class="grid2"><div class="field"><label>Sexo</label><select id="aSexo"><option value=""></option><option ${a?.SEXO==='MASCULINO'?'selected':''}>MASCULINO</option><option ${a?.SEXO==='FEMININO'?'selected':''}>FEMININO</option></select></div><div class="field"><label>Foto</label><input id="aFoto" type="file" accept="image/*" capture="environment"></div></div><button class="btn primary block" onclick="saveAuthority('${esc(id)}',${addAfter?'true':'false'})">SALVAR</button>`);}
async function saveAuthority(id,addAfter){const f=$('#aFoto').files[0],payload={ID_AUTORIDADE:id,POSTO:$('#aPosto').value,NOME_COMPLETO:$('#aNome').value,NOME_GUERRA:$('#aGuerra').value,CARGO_ATUAL:$('#aCargo').value,FORCA:$('#aForca').value,SITUACAO:$('#aSit').value,SEXO:$('#aSexo').value};if(f){payload.FOTO_NOME=f.name;payload.FOTO_MIME=f.type;payload.FOTO_BASE64=await readFile(f);}const a=await server('apiSalvarAutoridade',payload);closeModal();showToast('Autoridade salva.');if(addAfter){await openAddGuest();$('#agSearch').value=a.NOME_COMPLETO;await searchAuthorityForGuest();}else if(state.screen==='autoridades')renderAutoridades();}
function readFile(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f);});}

async function renderFamiliares(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const list=await server('apiListarFamiliares',c.ID_CERIMONIA,'TODOS');$('#main').innerHTML=`<div class="page-head"><div class="section-title">FAMILIARES — ${esc(c.NOME_EVENTO)}</div><button class="btn primary" onclick="openFamilyForm()">ADICIONAR</button></div>${familyList(list)}`;}
function familyList(list){if(!list.length)return'<div class="empty">Nenhum familiar cadastrado.</div>';return`<div class="person-list">${list.map(f=>`<div class="person-card clickable" onclick="openFamilyDetail('${f.ID_FAMILIAR}')"><div class="avatar placeholder">FAM.</div><div class="grow"><div class="person-name">${esc(f.NOME)}</div><div class="person-sub">${esc(f.VINCULO+' de '+f.AUTORIDADE)}</div></div><div class="person-right">${f.PRESENCA?'<span class="badge present">PRESENTE</span>':badgeStatus(f.STATUS_CONFIRMACAO)}</div></div>`).join('')}</div>`;}
async function openFamilyForm(id=''){const c=contextCeremony(),[fams,guests]=await Promise.all([server('apiListarFamiliares',c.ID_CERIMONIA,'TODOS'),server('apiListarConvidados',c.ID_CERIMONIA,'TODOS')]);const f=fams.find(x=>x.ID_FAMILIAR===id)||{};openModal(`${modalCloseButton()}<h2>${id?'Editar':'Adicionar'} familiar</h2><div class="field"><label>Nome</label><input id="fNome" value="${esc(f.NOME||'')}"></div><div class="grid2"><div class="field"><label>Vínculo</label><select id="fVinc">${['CÔNJUGE','FILHO','FILHA','PAI','MÃE','OUTRO'].map(x=>`<option ${f.VINCULO===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Precedência</label><input id="fPrec" type="number" value="${f.PRECEDENCIA<9999?f.PRECEDENCIA:''}"></div></div><div class="field"><label>Autoridade vinculada</label><select id="fAut">${guests.map(g=>`<option value="${esc(g.NOME_COMPLETO)}" ${f.AUTORIDADE===g.NOME_COMPLETO?'selected':''}>${esc(g.POSTO+' '+g.NOME_GUERRA)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="fStatus">${['CONFIRMADO','PENDENTE','NÃO COMPARECERÁ'].map(x=>`<option ${f.STATUS_CONFIRMACAO===x?'selected':''}>${x}</option>`).join('')}</select></div><button class="btn primary block" onclick="saveFamily('${id}')">SALVAR</button>`);}
async function saveFamily(id){const c=contextCeremony();await server('apiSalvarFamiliar',c.ID_CERIMONIA,{ID_FAMILIAR:id,NOME:$('#fNome').value,VINCULO:$('#fVinc').value,AUTORIDADE:$('#fAut').value,PRECEDENCIA:$('#fPrec').value,STATUS_CONFIRMACAO:$('#fStatus').value});closeModal();renderFamiliares();}
async function openFamilyDetail(id){const c=contextCeremony(),f=(await server('apiListarFamiliares',c.ID_CERIMONIA,'TODOS')).find(x=>x.ID_FAMILIAR===id);if(!f)return;openModal(`${modalCloseButton()}<h2>${esc(f.NOME)}</h2><p class="muted">${esc(f.VINCULO)} de ${esc(f.AUTORIDADE)}</p><dl class="detail-grid"><dt>Status</dt><dd>${badgeStatus(f.STATUS_CONFIRMACAO)}</dd><dt>Precedência</dt><dd>${f.PRECEDENCIA}</dd></dl><div class="actions">${f.PRESENCA?`<button class="btn danger" onclick="familyPresence('${id}',false)">CANCELAR PRESENÇA</button>`:`<button class="btn ok" onclick="familyPresence('${id}',true)">CONFIRMAR PRESENÇA</button>`}<button class="btn outline" onclick="addFamilyToNominata('${id}')">ADICIONAR À NOMINATA</button><button class="btn outline" onclick="openFamilyForm('${id}')">EDITAR</button><button class="btn danger" onclick="deleteFamily('${id}')">EXCLUIR</button></div>`);}
async function familyPresence(id,on){const c=contextCeremony();await server(on?'apiMarcarPresencaFamiliar':'apiCancelarPresencaFamiliar',c.ID_CERIMONIA,id);closeModal();renderFamiliares();}
async function addFamilyToNominata(id){const c=contextCeremony();await server('apiAdicionarItemNominata',{ID_CERIMONIA:c.ID_CERIMONIA,TIPO_ITEM:'FAMILIAR',REFERENCIA_ID:id});closeModal();showToast('Familiar adicionado à nominata.');}
async function deleteFamily(id){if(!confirm('Excluir este familiar?'))return;const c=contextCeremony();await server('apiExcluirFamiliar',c.ID_CERIMONIA,id);closeModal();renderFamiliares();}

async function renderTribuna(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const data=await server('apiObterTribuna',c.ID_CERIMONIA);let html=`<div class="section-title">TRIBUNA — ${esc(c.NOME_EVENTO)}</div><div class="card"><div class="grid3"><div class="field"><label>Lógica</label><select id="tLogic"><option value="IMPAR" ${data.config.LOGICA_TRIBUNA==='IMPAR'?'selected':''}>ÍMPAR</option><option value="PAR" ${data.config.LOGICA_TRIBUNA==='PAR'?'selected':''}>PAR</option></select></div><div class="field"><label>Fileiras</label><input id="tRows" type="number" min="1" max="3" value="${data.config.NUM_FILEIRAS}"></div><div class="field"><label>Pessoas por fileira</label><input id="tSeats" type="number" min="1" max="25" value="${data.config.QTD_POR_FILEIRA}"></div></div><button class="btn primary" onclick="saveTribunaConfig()">ATUALIZAR COMPOSIÇÃO</button></div>`;if(data.avisos?.length)html+=data.avisos.map(a=>`<div class="notice">${esc(a)}</div>`).join('');if(data.fileiras?.length)html+=`<div class="tribuna-wrap"><div class="tropa">FRENTE DA TROPA</div>${data.fileiras.map(fr=>`<div class="fileira-label">FILEIRA ${fr.numero}</div><div class="tribuna-row">${fr.posicoes.map(p=>`<div class="seat ${p.autoridade.PRESENCA?'arrived':''}"><div class="order">${esc(p.rotulo)}</div><div class="seat-name">${esc((p.autoridade.POSTO?p.autoridade.POSTO+' ':'')+(p.autoridade.NOME_GUERRA||p.autoridade.NOME_COMPLETO))}</div><div class="seat-role">${esc(p.funcao)}</div></div>`).join('')}</div>`).join('')}</div>`;else html+='<div class="empty">A composição ainda não pode ser exibida.</div>';$('#main').innerHTML=html;}
async function saveTribunaConfig(){const c=contextCeremony();await server('apiSalvarConfigTribuna',c.ID_CERIMONIA,{LOGICA_TRIBUNA:$('#tLogic').value,NUM_FILEIRAS:$('#tRows').value,QTD_POR_FILEIRA:$('#tSeats').value});renderTribuna();}

async function renderNominata(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const [items,guests,fams,msgs]=await Promise.all([server('apiListarNominata',c.ID_CERIMONIA),server('apiListarConvidados',c.ID_CERIMONIA,'TODOS'),server('apiListarFamiliares',c.ID_CERIMONIA,'TODOS'),server('apiListarMensagensNominata')]);state.nomData={guests,fams,msgs};let html=`<div class="page-head"><div class="section-title">NOMINATA — ${esc(c.NOME_EVENTO)}</div><div><button class="btn outline" onclick="openMessageBank()">MENSAGENS</button> <button class="btn primary" onclick="openAddNominataItem()">ADICIONAR ITEM</button></div></div>`;if(!items.length)html+='<div class="empty">A nominata está vazia.</div>';else html+=`<div class="person-list">${items.map(i=>`<div class="person-card"><div class="avatar placeholder">${i.ORDEM}</div><div class="grow"><div class="person-name">${esc(i.TITULO)}</div><div class="person-sub">${esc(i.TIPO_ITEM)}${i.PRESENTE===false?' | presença ainda não registrada':''}</div></div><div class="order-controls"><button onclick="moveNom('${i.ID_ITEM}',-1)">SUBIR</button><button onclick="moveNom('${i.ID_ITEM}',1)">DESCER</button><button onclick="removeNom('${i.ID_ITEM}')">REMOVER</button></div></div>`).join('')}</div>`;$('#main').innerHTML=html;}
function openAddNominataItem(){const d=state.nomData||{guests:[],fams:[],msgs:[]};openModal(`${modalCloseButton()}<h2>Adicionar item à nominata</h2><div class="field"><label>Tipo</label><select id="nType" onchange="updateNomRef()"><option value="AUTORIDADE">Autoridade</option><option value="FAMILIAR">Familiar</option><option value="MENSAGEM">Mensagem predefinida</option><option value="TEXTO">Texto livre</option></select></div><div class="field" id="nRefWrap"><label>Referência</label><select id="nRef"></select></div><div class="field" id="nTextWrap"><label>Texto livre / complemento</label><textarea id="nText"></textarea></div><button class="btn primary block" onclick="submitNomItem()">ADICIONAR</button>`);updateNomRef();}
function updateNomRef(){const type=$('#nType').value,d=state.nomData||{};let opts='';if(type==='AUTORIDADE')opts=(d.guests||[]).map(g=>`<option value="${g.ID_CONVIDADO}">${esc(g.POSTO+' '+g.NOME_GUERRA)}</option>`).join('');if(type==='FAMILIAR')opts=(d.fams||[]).map(f=>`<option value="${f.ID_FAMILIAR}">${esc(f.NOME+' — '+f.VINCULO)}</option>`).join('');if(type==='MENSAGEM')opts=(d.msgs||[]).map(m=>`<option value="${m.ID_MENSAGEM}">${esc(m.TEXTO)}</option>`).join('');$('#nRef').innerHTML=opts;$('#nRefWrap').classList.toggle('hidden',type==='TEXTO');}
async function submitNomItem(){const c=contextCeremony();await server('apiAdicionarItemNominata',{ID_CERIMONIA:c.ID_CERIMONIA,TIPO_ITEM:$('#nType').value,REFERENCIA_ID:$('#nRef').value,TEXTO_CUSTOMIZADO:$('#nText').value});closeModal();renderNominata();}
async function moveNom(id,d){const c=contextCeremony();await server('apiMoverItemNominata',c.ID_CERIMONIA,id,d);renderNominata();}async function removeNom(id){const c=contextCeremony();await server('apiRemoverItemNominata',c.ID_CERIMONIA,id);renderNominata();}
async function openMessageBank(){const msgs=await server('apiListarMensagensNominata');openModal(`${modalCloseButton()}<h2>Mensagens predefinidas</h2><div class="field"><label>Nova mensagem</label><textarea id="mbText"></textarea></div><button class="btn primary" onclick="addMessageBank()">ADICIONAR</button><div class="section-title">CADASTRADAS</div>${msgs.map(m=>`<div class="row between card"><div class="small">${esc(m.TEXTO)}</div><button class="btn danger sm" onclick="deleteMessageBank('${m.ID_MENSAGEM}')">EXCLUIR</button></div>`).join('')}`);}
async function addMessageBank(){await server('apiAdicionarMensagemPadrao',$('#mbText').value);closeModal();await renderNominata();showToast('Mensagem adicionada.');}
async function deleteMessageBank(id){await server('apiExcluirMensagemPadrao',id);closeModal();await renderNominata();showToast('Mensagem removida.');}

async function renderEstatisticas(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}const rows=await server('apiEstatisticas',c.ID_CERIMONIA);$('#main').innerHTML=`<div class="page-head"><div class="section-title">ESTATÍSTICAS POR CÍRCULO</div><button class="btn outline" onclick="openStatsConfig()">CONFIGURAR CÍRCULOS</button></div><div class="stats-wrap"><table class="stats"><thead><tr><th>GRUPO</th><th>CONF.</th><th>PRES.</th><th>PEND.</th><th>NÃO VIRÁ</th><th>TOTAL</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.GRUPO)}</td><td>${r.CONFIRMADOS}</td><td><strong>${r.PRESENTES}</strong></td><td>${r.PENDENTES}</td><td>${r.NAO_COMPARECERA}</td><td><strong>${r.TOTAL}</strong></td></tr>`).join('')}</tbody></table></div>`;}
async function openStatsConfig(){const c=contextCeremony(),[groups,opts]=await Promise.all([server('apiListarGruposEstatistica'),server('apiOpcoesEstatistica',c.ID_CERIMONIA)]);state.statsConfig={groups,opts};openModal(`${modalCloseButton()}<h2>Configurar círculos estatísticos</h2><p class="small muted">Você pode acrescentar postos e também autoridades específicas a cada círculo. Uma autoridade adicionada nominalmente prevalece sobre a classificação automática por posto/força.</p>${groups.filter(g=>g.tipo==='CONVIDADOS').map(g=>statsGroupHtml(g,opts)).join('')}`);}
function statsGroupHtml(g,opts){return `<div class="circle-card"><div class="title">${esc(g.nome)}</div><div class="small muted">Postos cadastrados</div><div class="chips">${(g.postos||[]).map(p=>`<span class="chip">${esc(p)}<button onclick="removePostFromGroup('${g.id}','${esc(p)}')">X</button></span>`).join('')||'<span class="small muted">Nenhum posto específico.</span>'}</div><div class="row"><select id="posto_${g.id}" class="grow">${opts.postos.map(p=>`<option>${esc(p)}</option>`).join('')}</select><button class="btn outline sm" onclick="addPostToGroup('${g.id}')">ADICIONAR POSTO</button></div><div class="small muted" style="margin-top:10px">Autoridades específicas</div><div class="chips">${(g.autoridades||[]).map(id=>{const a=opts.autoridades.find(x=>x.ID_AUTORIDADE===id);return`<span class="chip">${esc(a?a.NOME:id)}<button onclick="removeAuthorityFromGroup('${g.id}','${id}')">X</button></span>`}).join('')||'<span class="small muted">Nenhuma autoridade específica.</span>'}</div><div class="row"><select id="aut_${g.id}" class="grow">${opts.autoridades.map(a=>`<option value="${a.ID_AUTORIDADE}">${esc(a.NOME)}</option>`).join('')}</select><button class="btn outline sm" onclick="addAuthorityToGroup('${g.id}')">ADICIONAR AUTORIDADE</button></div></div>`;}
async function addPostToGroup(id){const p=$('#posto_'+id).value;if(p)await server('apiAdicionarPostoGrupo',id,p);openStatsConfig();}
async function removePostFromGroup(id,p){await server('apiRemoverPostoGrupo',id,p);openStatsConfig();}
async function addAuthorityToGroup(id){const a=$('#aut_'+id).value;if(a)await server('apiAdicionarAutoridadeGrupo',id,a);openStatsConfig();}
async function removeAuthorityFromGroup(id,a){await server('apiRemoverAutoridadeGrupo',id,a);openStatsConfig();}

async function renderDocumentos(){const c=contextCeremony();if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;}$('#main').innerHTML=`<div class="section-title">GERAR ARQUIVOS — ${esc(c.NOME_EVENTO)}</div><div class="card"><p class="small muted">Os arquivos são gerados com os dados atuais da cerimônia e recebem o rodapé do SGCM 2.0.</p><div class="actions"><button class="btn primary" onclick="genDoc('nominata')">GERAR ANEXO À LOCUÇÃO</button><button class="btn primary" onclick="genDoc('tribuna')">GERAR TRIBUNA DE HONRA</button></div><div id="docResult"></div></div>`;}
async function genDoc(type){const c=contextCeremony();$('#docResult').innerHTML='<p class="small muted">Gerando documento...</p>';try{const r=await server(type==='tribuna'?'apiGerarTribunaDocumento':'apiGerarNominata',c.ID_CERIMONIA);$('#docResult').innerHTML=`<p><a class="btn outline" href="${esc(r.url)}" target="_blank">ABRIR DOCUMENTO GERADO</a></p><p class="small muted">${esc(r.nome)}</p>`;}catch(e){$('#docResult').innerHTML=`<div class="notice danger-notice">${esc(e.message)}</div>`;}}

function renderGuia(){$('#main').innerHTML=`<div class="section-title">GUIA RÁPIDO</div><div class="card"><p><b>Planejamento na planilha.</b> Cada cerimônia possui duas abas próprias: Cxxx_CONVIDADOS e Cxxx_FAMILIARES. Na aba de convidados, cole POSTO, NOME_COMPLETO e NOME_GUERRA, organize a precedência e defina CONFIRMADO, PENDENTE ou NÃO COMPARECERÁ.</p><p><b>Banco permanente.</b> AUTORIDADES mantém o cadastro e as fotos. Se um nome colado não existir no banco, os dados derivados ficam em branco; ao cadastrar a autoridade, as fórmulas completam a linha da cerimônia.</p><p><b>Várias cerimônias.</b> Podem existir várias em STANDBY, cada uma com suas próprias abas, mas o backend permite somente uma ATIVA.</p><p><b>Operação.</b> Recepção, Presentes, Tribuna, Nominata, Estatísticas e documentos trabalham exclusivamente com a cerimônia ATIVA.</p><p><b>Estatísticas.</b> São separadas por Autoridades Civis, Familiares, 4 Estrelas, 3 Estrelas, 2 Estrelas e Oficiais Superiores. Em Configurar Círculos, você pode acrescentar novos postos ou autoridades específicas aos grupos.</p><p><b>Fotos.</b> A instalação usa apenas a sua própria pasta AUTORIDADES_Images. Copie as fotos preservando os nomes e use SGCM > Indexar fotografias.</p></div>`;}
boot();